In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
file_path = Path("../data/Coffee_Shop_Sales.xlsx")

df = pd.read_excel(
    file_path,
    sheet_name="DATA_MESSY"
)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
print("Dataset shape:", df.shape)

display(df.head())

Dataset shape: (149416, 12)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Revenue
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.0
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.0
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.0
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149416 entries, 0 to 149415
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149416 non-null  int64
 1   transaction_date  149416 non-null  datetime64[ns]
 2   transaction_time  149165 non-null  object
 3   transaction_qty   149416 non-null  int64
 4   store_id          149416 non-null  int64
 5   store_location    149265 non-null  object
 6   product_id        149416 non-null  int64
 7   unit_price        149416 non-null  object
 8   product_category  149115 non-null  object
 9   product_type      149416 non-null  object
 10  product_detail    149416 non-null  object
 11  Revenue           149416 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(4), object(6)
memory usage: 13.7+ MB

In [5]:
print("Missing values per column:")
display(df.isna().sum())

print("Exact duplicate rows:", df.duplicated().sum())

Missing values per column:

transaction_id        0
transaction_date      0
transaction_time    251
transaction_qty       0
store_id              0
store_location      151
product_id            0
unit_price            0
product_category    301
product_type          0
product_detail        0
Revenue               0
dtype: int64

Exact duplicate rows: 300

In [6]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
display(df.dtypes)

Rows: 149416
Columns: 12

Column names:
['transaction_id', 'transaction_date', 'transaction_time', 'transaction_qty', 'store_id', 'store_location', 'product_id', 'unit_price', 'product_category', 'product_type', 'product_detail', 'Revenue']

Data types:

transaction_id               int64
transaction_date    datetime64[ns]
transaction_time            object
transaction_qty              int64
store_id                     int64
store_location              object
product_id                   int64
unit_price                  object
product_category            object
product_type                object
product_detail              object
Revenue                    float64
dtype: object

In [7]:
missing = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (
        df.isna().mean() * 100
    ).round(2)
})

display(missing.sort_values(
    "Missing_Count",
    ascending=False
))

                  Missing_Count  Missing_Percentage
product_category            301                0.20
transaction_time            251                0.17
store_location              151                0.10
transaction_id                0                0.00
transaction_qty               0                0.00
transaction_date              0                0.00
product_id                    0                0.00
store_id                      0                0.00
unit_price                    0                0.00
product_type                  0                0.00
product_detail                0                0.00
Revenue                       0                0.00

In [8]:
print("Exact duplicate rows:", df.duplicated().sum())

display(df[df.duplicated(keep=False)].head(10))

Exact duplicate rows: 300

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Revenue
256,257,2023-01-01,13:42:58,1,5,Lower Manhattan,72,3.25,Bakery,Scone,Ginger Scone,3.25
800,801,2023-01-02,13:42:07,1,8,Hell's Kitchen,36,3.75,Coffee,Premium brewed coffee,Jamaican Coffee River Lg,3.75
1508,1509,2023-01-03,16:08:18,1,8,Hell's Kitchen,47,3,Tea,Brewed Green tea,Serenity Green Tea Lg,3.00
1608,1609,2023-01-03,17:44:32,1,3,Astoria,38,3.75,Coffee,Barista Espresso,Latte,3.75
3350,3380,2023-01-07,08:34:42,1,5,Lower Manhattan,79,3.75,Bakery,Scone,Jumbo Savory Scone,3.75
3529,3559,2023-01-07,10:36:38,2,3,Astoria,41,4.25,Coffee,Barista Espresso,Cappuccino Lg,8.50
3645,3675,2023-07-01,12:53:48,2,5,Lower Manhattan,61,4.75,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Lg,9.50
3716,3746,2023-01-07,16:24:34,1,8,Hell's Kitchen,23,2.5,Coffee,Drip coffee,Our Old Time Diner Blend Rg,2.50
3775,3805,2023-01-07,18:47:28,2,8,Hell's Kitchen,52,2.5,Tea,Brewed Chai tea,Traditional Blend Chai Rg,5.00
5373,5403,2023-01-10,13:35:10,1,8,Hell's Kitchen,37,3,Coffee,Barista Espresso,Espresso shot,3.00

In [9]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
transaction_id,149416.0,NaN,NaN,NaN,74735.950956,1.0,37335.75,74728.5,112085.25,149456.0,43152.289668
transaction_date,149416,NaN,NaN,NaN,2023-04-15 13:12:05.319911936,2023-01-01 00:00:00,2023-03-06 00:00:00,2023-04-24 00:00:00,2023-05-30 00:00:00,2023-12-06 00:00:00,NaN
transaction_time,149165,25761,09:31:15,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transaction_qty,149416.0,NaN,NaN,NaN,1.436847,-2.0,1.0,1.0,2.0,8.0,0.545798
store_id,149416.0,NaN,NaN,NaN,5.342493,3.0,3.0,5.0,8.0,8.0,2.074129
store_location,149265,3,Hell's Kitchen,50785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_id,149416.0,NaN,NaN,NaN,47.919922,1.0,33.0,47.0,60.0,87.0,17.93095
unit_price,149416.0,64.0,3.0,33744.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category,149115,18,Coffee,58232,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_type,149416,29,Brewed Chai tea,17219,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_detail,149416,142,Chocolate Croissant,3079,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Revenue,149416.0,NaN,NaN,NaN,4.686637,0.8,3.0,3.75,6.0,360.0,4.22809

In [10]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False).head(10))

transaction_time
transaction_time
NaN         251
09:31:15     41
08:15:41     40
08:19:08     38
11:40:03     36
10:11:25     36
10:34:04     36
09:44:57     35
08:08:13     35
10:08:24     35
Name: count, dtype: int64

store_location
store_location
Hell's Kitchen     50785
Astoria            50637
Lower Manhattan    47843
NaN                  151
Name: count, dtype: int64

unit_price
unit_price
3       33744
2.5     26360
3.75    18493
3.5     13734
0.8      6797
3.25     6059
4.25     5682
2        5650
2.2      5648
3.1      5549
Name: count, dtype: int64

product_category
product_category
Coffee                58232
Tea                   45343
Bakery                22750
Drinking Chocolate    11439
Flavours               6770
Coffee beans           1746
Loose Tea              1204
Branded                 745
Packaged Chocolate      487
NaN                     301
Name: count, dtype: int64

product_type
product_type
Brewed Chai tea          17219
Gourmet brewed coffee    16950
Barista Espresso         16438
Hot chocolate            11488
Brewed Black tea         11370
Brewed herbal tea        11264
Scone                    10193
Organic brewed coffee     8502
Drip coffee               8501
Premium brewed coffee     8148
Name: count, dtype: int64

product_detail
product_detail
Chocolate Croissant             3079
Earl Grey Rg                    3054
Morning Sunrise Chai Rg         3024
Dark chocolate Lg               3019
Columbian Medium Roast Rg       3018
Latte                           2987
Sustainably Grown Organic Lg    2964
Traditional Blend Chai Rg       2956
Spicy Eye Opener Chai Lg        2953
Peppermint Rg                   2949
Name: count, dtype: int64

In [11]:
print("Unit price data type:", df["unit_price"].dtype)

price_as_number = pd.to_numeric(
    df["unit_price"].astype(str).str.strip(),
    errors="coerce"
)

print("Values that cannot be converted to numbers:",
      price_as_number.isna().sum())

print("Non-positive prices:",
      (price_as_number <= 0).sum())

Unit price data type: object
Values that cannot be converted to numbers: 201
Non-positive prices: 0

In [12]:
negative_qty = df[df["transaction_qty"] <= 0]

print("Non-positive quantity rows:", len(negative_qty))

display(negative_qty.head(20))

Non-positive quantity rows: 100

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Revenue
844,845,2023-01-02,14:33:58,-2,5,Lower Manhattan,37,3,Coffee,Barista Espresso,Espresso shot,6.00
1943,1944,2023-01-04,14:21:46,0,3,Astoria,53,3,Tea,Brewed Chai tea,Traditional Blend Chai Lg,6.00
2858,2859,2023-01-06,11:05:28,-1,8,Hell's Kitchen,36,3.75,Coffee,Premium brewed coffee,Jamaican Coffee River Lg,3.75
3663,3693,2023-01-07,13:38:18,-1,3,Astoria,35,3.1,Coffee,Premium brewed coffee,Jamaican Coffee River Rg,3.10
4378,4408,2023-01-09,06:39:11,0,8,Hell's Kitchen,76,3.5,Bakery,Biscotti,Chocolate Chip Biscotti,3.50
10011,10041,2023-01-18,10:55:31,-2,3,Astoria,50,2.5,Tea,Brewed Black tea,Earl Grey Rg,5.00
11147,11177,2023-01-20,10:28:53,-2,5,Lower Manhattan,87,3,Coffee,Barista Espresso,Ouro Brasileiro shot,6.00
12978,13008,2023-01-23,16:20:30,-1,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,3.10
16802,16832,2023-01-30,17:29:02,-1,3,Astoria,9,22.5,Coffee beans,Organic Beans,Organic Decaf Blend,22.50
18010,18040,2023-02-02,12:01:04,-2,5,Lower Manhattan,55,4,Tea,Brewed Chai tea,Morning Sunrise Chai Lg,8.00
19237,19267,2023-02-04,12:50:19,0,5,Lower Manhattan,34,2.45,Coffee,Premium brewed coffee,Jamaican Coffee River Sm,4.90
19683,19713,2023-02-05,09:57:32,-1,5,Lower Manhattan,70,3.25,Bakery,Scone,Cranberry Scone,3.25
19961,19991,2023-02-05,15:52:10,0,8,Hell's Kitchen,54,2.5,Tea,Brewed Chai tea,Morning Sunrise Chai Rg,2.50
22630,22687,2023-02-10,10:00:26,-1,3,Astoria,29,2.5,Coffee,Gourmet brewed coffee,Columbian Medium Roast Rg,2.50
26973,27030,2023-02-17,13:26:01,-1,3,Astoria,48,2.5,Tea,Brewed Black tea,English Breakfast Rg,2.50
27710,27767,2023-02-19,06:08:41,0,5,Lower Manhattan,25,2.2,Coffee,Organic brewed coffee,Brazilian Sm,2.20
29285,29342,2023-02-21,10:14:51,0,8,Hell's Kitchen,41,4.25,Coffee,Barista Espresso,Cappuccino Lg,8.50
30062,30119,2023-02-22,16:40:39,0,5,Lower Manhattan,51,3,Tea,Brewed Black tea,Earl Grey Lg,3.00
33225,33282,2023-02-28,08:46:26,0,3,Astoria,31,2.2,Coffee,Gourmet brewed coffee,Ethiopia Sm,4.40
34025,34082,2023-03-01,14:34:35,-2,3,Astoria,52,2.5,Tea,Brewed Chai tea,Traditional Blend Chai Rg,5.00

In [13]:
for col in ["store_location", "product_category"]:
    print(f"\n--- {col} ---")

    values = df[col].dropna().astype(str)

    print("Unique values:", values.nunique())
    print("Values with extra spaces:",
          (values != values.str.strip()).sum())

    print("Values with inconsistent capitalization:")
    display(values[
        values != values.str.strip().str.title()
    ].drop_duplicates().head(20))

--- store_location ---
Unique values: 3
Values with extra spaces: 0
Values with inconsistent capitalization:

17    Hell's Kitchen
Name: store_location, dtype: object

--- product_category ---
Unique values: 18
Values with extra spaces: 0
Values with inconsistent capitalization:

134                      TEA
465                   BAKERY
1315                  COFFEE
1663      DRINKING CHOCOLATE
3293            Coffee beans
4805                FLAVOURS
4825            COFFEE BEANS
6434               LOOSE TEA
25034                BRANDED
125192    PACKAGED CHOCOLATE
Name: product_category, dtype: object

In [15]:
check = df.copy()

check["unit_price_numeric"] = pd.to_numeric(
    check["unit_price"].astype(str).str.strip(),
    errors="coerce"
)

check["expected_revenue"] = (
    check["transaction_qty"] *
    check["unit_price_numeric"]
)

check["revenue_difference"] = (
    check["Revenue"] - check["expected_revenue"]
).abs()

print(
    "Rows with revenue mismatch:",
    (check["revenue_difference"] > 0.01).sum()
)

display(
    check.loc[
        check["revenue_difference"] > 0.01,
        [
            "transaction_qty",
            "unit_price",
            "Revenue",
            "expected_revenue"
        ]
    ].head(10)
)

Rows with revenue mismatch: 100

       transaction_qty unit_price  Revenue  expected_revenue
844                 -2          3     6.00             -6.00
1943                 0          3     6.00              0.00
2858                -1       3.75     3.75             -3.75
3663                -1        3.1     3.10             -3.10
4378                 0        3.5     3.50              0.00
10011               -2        2.5     5.00             -5.00
11147               -2          3     6.00             -6.00
12978               -1        3.1     3.10             -3.10
16802               -1       22.5    22.50            -22.50
18010               -2          4     8.00             -8.00

In [16]:
# Keep the original data unchanged
df_clean = df.copy()

print("Original rows:", len(df))
print("Working copy rows:", len(df_clean))

Original rows: 149416
Working copy rows: 149416

In [17]:
text_columns = [
    "store_location",
    "product_category",
    "product_type",
    "product_detail"
]

for col in text_columns:
    df_clean[col] = df_clean[col].astype("string").str.strip()

# Normalize category and location labels
for col in ["store_location", "product_category"]:
    df_clean[col] = df_clean[col].str.title()

print("Text standardization complete.")

Text standardization complete.

In [19]:
# Convert price to a numeric type
df_clean["unit_price"] = pd.to_numeric(
    df_clean["unit_price"].astype("string").str.strip(),
    errors="coerce"
)

# Ensure the date column uses datetime
df_clean["transaction_date"] = pd.to_datetime(
    df_clean["transaction_date"],
    errors="coerce"
)

# Standardize the time column
df_clean["transaction_time"] = pd.to_datetime(
    df_clean["transaction_time"].astype("string").str.strip(),
    format="%H:%M:%S",
    errors="coerce"
).dt.time

print(df_clean[
    ["transaction_date", "transaction_time", "unit_price"]
].dtypes)

transaction_date    datetime64[ns]
transaction_time            object
unit_price                 Float64
dtype: object

In [20]:
duplicates_before = df_clean.duplicated().sum()

df_clean = df_clean.drop_duplicates().copy()

duplicates_after = df_clean.duplicated().sum()

print("Duplicates before:", duplicates_before)
print("Duplicates removed:", duplicates_before - len(df_clean) if False else duplicates_before - duplicates_after)
print("Duplicates remaining:", duplicates_after)
print("Rows after deduplication:", len(df_clean))

Duplicates before: 300
Duplicates removed: 300
Duplicates remaining: 0
Rows after deduplication: 149116

In [21]:
quality_summary = pd.DataFrame({
    "Missing_Count": df_clean.isna().sum(),
    "Missing_Percentage": (
        df_clean.isna().mean() * 100
    ).round(2)
})

display(quality_summary.sort_values(
    "Missing_Count",
    ascending=False
))

print("Remaining exact duplicates:", df_clean.duplicated().sum())
print("Cleaned DataFrame shape:", df_clean.shape)

                  Missing_Count  Missing_Percentage
product_category            300                0.20
transaction_time            250                0.17
unit_price                  200                0.13
store_location              150                0.10
transaction_qty               0                0.00
transaction_date              0                0.00
transaction_id                0                0.00
store_id                      0                0.00
product_id                    0                0.00
product_type                  0                0.00
product_detail                0                0.00
Revenue                       0                0.00

Remaining exact duplicates: 0
Cleaned DataFrame shape: (149116, 12)

In [22]:
missing_rows = df_clean[df_clean.isna().any(axis=1)]

print("Rows containing missing values:", len(missing_rows))

display(missing_rows.head(20))

Rows containing missing values: 897

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Revenue
225,226,2023-01-01,13:04:51,1,3,<NA>,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00
346,347,2023-01-01,15:29:24,1,3,Astoria,57,3.1,<NA>,Brewed Chai tea,Spicy Eye Opener Chai Lg,3.10
415,416,2023-01-01,17:05:44,2,3,Astoria,36,<NA>,Coffee,Premium brewed coffee,Jamaican Coffee River Lg,7.50
584,585,2023-01-02,NaT,1,8,Hell'S Kitchen,35,3.1,Coffee,Premium brewed coffee,Jamaican Coffee River Rg,3.10
782,783,2023-01-02,NaT,1,3,Astoria,47,3.0,Tea,Brewed Green tea,Serenity Green Tea Lg,3.00
817,818,2023-01-02,14:02:16,2,8,Hell'S Kitchen,25,<NA>,Coffee,Organic brewed coffee,Brazilian Sm,4.40
899,900,2023-01-02,NaT,2,3,Astoria,23,2.5,Coffee,Drip coffee,Our Old Time Diner Blend Rg,5.00
1077,1078,2023-01-02,NaT,2,3,Astoria,52,2.5,Tea,Brewed Chai tea,Traditional Blend Chai Rg,5.00
1308,1309,2023-01-03,12:51:17,2,8,Hell'S Kitchen,49,3.0,<NA>,Brewed Black tea,English Breakfast Lg,6.00
1572,1573,2023-01-03,17:06:38,2,8,<NA>,39,4.25,Coffee,Barista Espresso,Latte Rg,8.50
1609,1610,2023-01-03,17:53:41,1,3,Astoria,52,<NA>,Tea,Brewed Chai tea,Traditional Blend Chai Rg,2.50
1765,1766,2023-01-04,10:19:21,2,8,<NA>,87,3.0,Coffee,Barista Espresso,Ouro Brasileiro shot,6.00
1982,1983,2023-01-04,NaT,1,3,Astoria,76,3.5,Bakery,Biscotti,Chocolate Chip Biscotti,3.50
2083,2084,2023-01-04,17:27:18,2,3,Astoria,59,<NA>,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00
2259,2260,2023-01-05,09:27:28,2,5,Lower Manhattan,25,<NA>,Coffee,Organic brewed coffee,Brazilian Sm,4.40
2420,2421,2023-01-05,NaT,1,8,Hell'S Kitchen,41,4.25,Coffee,Barista Espresso,Cappuccino Lg,4.25
2650,2651,2023-01-05,17:28:31,2,3,Astoria,37,<NA>,Coffee,Barista Espresso,Espresso shot,6.00
2745,2746,2023-01-06,07:05:49,2,5,Lower Manhattan,37,<NA>,Coffee,Barista Espresso,Espresso shot,6.00
2761,2762,2023-01-06,07:56:38,1,5,Lower Manhattan,71,3.75,<NA>,Pastry,Chocolate Croissant,3.75
2918,2919,2023-01-06,12:28:03,2,8,<NA>,23,2.5,Coffee,Drip coffee,Our Old Time Diner Blend Rg,5.00

In [23]:
# Check whether each product ID maps to one category
category_mapping = (
    df_clean.groupby("product_id")["product_category"]
    .nunique()
)

print(
    "Product IDs linked to multiple categories:",
    (category_mapping > 1).sum()
)

# Check whether each store ID maps to one location
store_mapping = (
    df_clean.groupby("store_id")["store_location"]
    .nunique()
)

print(
    "Store IDs linked to multiple locations:",
    (store_mapping > 1).sum()
)

Product IDs linked to multiple categories: 0
Store IDs linked to multiple locations: 0

In [24]:
# Build mappings from known, non-missing values
product_category_map = (
    df_clean.dropna(subset=["product_category"])
    .drop_duplicates("product_id")
    .set_index("product_id")["product_category"]
)

store_location_map = (
    df_clean.dropna(subset=["store_location"])
    .drop_duplicates("store_id")
    .set_index("store_id")["store_location"]
)

# Fill missing values only when a matching ID has a known value
df_clean["product_category"] = df_clean["product_category"].fillna(
    df_clean["product_id"].map(product_category_map)
)

df_clean["store_location"] = df_clean["store_location"].fillna(
    df_clean["store_id"].map(store_location_map)
)

print("Remaining missing categories:", df_clean["product_category"].isna().sum())
print("Remaining missing store locations:", df_clean["store_location"].isna().sum())

Remaining missing categories: 0
Remaining missing store locations: 0

In [25]:
print(
    "Missing transaction times:",
    df_clean["transaction_time"].isna().sum()
)

Missing transaction times: 250

In [26]:
print("Zero or negative quantities:",
      (df_clean["transaction_qty"] <= 0).sum())

print("Zero or negative prices:",
      (df_clean["unit_price"] <= 0).sum())

print("Missing prices:",
      df_clean["unit_price"].isna().sum())

Zero or negative quantities: 100
Zero or negative prices: 0
Missing prices: 200

In [27]:
quality_report = pd.DataFrame({
    "Missing_Count": df_clean.isna().sum(),
    "Missing_Percentage": (
        df_clean.isna().mean() * 100
    ).round(2)
})

display(quality_report)

                  Missing_Count  Missing_Percentage
transaction_id                0                0.00
transaction_date              0                0.00
transaction_time            250                0.17
transaction_qty               0                0.00
store_id                      0                0.00
store_location                0                0.00
product_id                    0                0.00
unit_price                  200                0.13
product_category              0                0.00
product_type                  0                0.00
product_detail                0                0.00
Revenue                       0                0.00

In [28]:
# Check the cleaned dataset
print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))
print("Exact duplicates:", df_clean.duplicated().sum())

print("\nMissing values:")
display(df_clean.isna().sum())

print("\nData types:")
display(df_clean.dtypes)

Rows: 149116
Columns: 12
Exact duplicates: 0

Missing values:

transaction_id        0
transaction_date      0
transaction_time    250
transaction_qty       0
store_id              0
store_location        0
product_id            0
unit_price          200
product_category      0
product_type          0
product_detail        0
Revenue               0
dtype: int64

Data types:

transaction_id               int64
transaction_date    datetime64[ns]
transaction_time            object
transaction_qty              int64
store_id                     int64
store_location      string[python]
product_id                   int64
unit_price                 Float64
product_category    string[python]
product_type        string[python]
product_detail      string[python]
Revenue                    float64
dtype: object

In [29]:
print("Non-positive quantities:",
      (df_clean["transaction_qty"] <= 0).sum())

print("Non-positive prices:",
      (df_clean["unit_price"] <= 0).sum())

print("Missing prices:",
      df_clean["unit_price"].isna().sum())

display(
    df_clean[
        (df_clean["transaction_qty"] <= 0) |
        (df_clean["unit_price"] <= 0) |
        (df_clean["unit_price"].isna())
    ].head(20)
)

Non-positive quantities: 100
Non-positive prices: 0
Missing prices: 200

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Revenue
415,416,2023-01-01,17:05:44,2,3,Astoria,36,<NA>,Coffee,Premium brewed coffee,Jamaican Coffee River Lg,7.50
817,818,2023-01-02,14:02:16,2,8,Hell'S Kitchen,25,<NA>,Coffee,Organic brewed coffee,Brazilian Sm,4.40
844,845,2023-01-02,14:33:58,-2,5,Lower Manhattan,37,3.0,Coffee,Barista Espresso,Espresso shot,6.00
1609,1610,2023-01-03,17:53:41,1,3,Astoria,52,<NA>,Tea,Brewed Chai tea,Traditional Blend Chai Rg,2.50
1943,1944,2023-01-04,14:21:46,0,3,Astoria,53,3.0,Tea,Brewed Chai tea,Traditional Blend Chai Lg,6.00
2083,2084,2023-01-04,17:27:18,2,3,Astoria,59,<NA>,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00
2259,2260,2023-01-05,09:27:28,2,5,Lower Manhattan,25,<NA>,Coffee,Organic brewed coffee,Brazilian Sm,4.40
2650,2651,2023-01-05,17:28:31,2,3,Astoria,37,<NA>,Coffee,Barista Espresso,Espresso shot,6.00
2745,2746,2023-01-06,07:05:49,2,5,Lower Manhattan,37,<NA>,Coffee,Barista Espresso,Espresso shot,6.00
2858,2859,2023-01-06,11:05:28,-1,8,Hell'S Kitchen,36,3.75,Coffee,Premium brewed coffee,Jamaican Coffee River Lg,3.75
3663,3693,2023-01-07,13:38:18,-1,3,Astoria,35,3.1,Coffee,Premium brewed coffee,Jamaican Coffee River Rg,3.10
4035,4065,2023-01-08,10:24:30,2,5,Lower Manhattan,35,<NA>,Coffee,Premium brewed coffee,Jamaican Coffee River Rg,6.20
4378,4408,2023-01-09,06:39:11,0,8,Hell'S Kitchen,76,3.5,Bakery,Biscotti,Chocolate Chip Biscotti,3.50
5180,5210,2023-01-10,09:20:27,1,3,Astoria,69,<NA>,Bakery,Biscotti,Hazelnut Biscotti,3.25
5222,5252,2023-01-10,09:45:23,1,3,Astoria,57,<NA>,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,3.10
6585,6615,2023-01-12,17:56:04,1,3,Astoria,15,<NA>,Loose Tea,Green tea,Serenity Green Tea,9.25
6591,6621,2023-01-12,18:18:49,2,5,Lower Manhattan,44,<NA>,Tea,Brewed herbal tea,Peppermint Rg,5.00
6752,6782,2023-01-13,08:35:27,2,8,Hell'S Kitchen,54,<NA>,Tea,Brewed Chai tea,Morning Sunrise Chai Rg,5.00
7042,7072,2023-01-13,12:05:51,2,5,Lower Manhattan,42,<NA>,Tea,Brewed herbal tea,Lemon Grass Rg,5.00
8482,8512,2023-01-15,19:44:02,2,3,Astoria,44,<NA>,Tea,Brewed herbal tea,Peppermint Rg,5.00

In [30]:
df_clean["expected_revenue"] = (
    df_clean["transaction_qty"] * df_clean["unit_price"]
)

df_clean["revenue_difference"] = (
    df_clean["Revenue"] - df_clean["expected_revenue"]
).abs()

mismatches = df_clean[
    df_clean["revenue_difference"] > 0.01
]

print("Revenue mismatches:", len(mismatches))

display(
    mismatches[
        [
            "transaction_qty",
            "unit_price",
            "Revenue",
            "expected_revenue"
        ]
    ].head(10)
)

Revenue mismatches: 100

       transaction_qty  unit_price  Revenue  expected_revenue
844                 -2         3.0     6.00              -6.0
1943                 0         3.0     6.00               0.0
2858                -1        3.75     3.75             -3.75
3663                -1         3.1     3.10              -3.1
4378                 0         3.5     3.50               0.0
10011               -2         2.5     5.00              -5.0
11147               -2         3.0     6.00              -6.0
12978               -1         3.1     3.10              -3.1
16802               -1        22.5    22.50             -22.5
18010               -2         4.0     8.00              -8.0

In [31]:
from pathlib import Path

output_dir = Path("../data")
output_dir.mkdir(parents=True, exist_ok=True)

In [32]:
output_path = output_dir / "coffee_shop_cleaned.csv"

df_clean.to_csv(output_path, index=False)

print("Saved to:", output_path.resolve())

Saved to: C:\omkar\Data Analysis project\Sales-Data-Analysis\data\coffee_shop_cleaned.csv

## Reproducible final cleaning and review outputs

Run the following cell from any working directory. It reloads the original `DATA_MESSY` sheet, documents each deterministic correction, and writes (1) an analysis CSV containing valid positive-quantity records and (2) a review CSV containing all nonpositive-quantity rows with their original values. Exact duplicate rows are counted and deduplicated once; no invalid-quantity record is silently removed. Dollar signs are formatting and are safely removed from price strings. Revenue is retained as recorded. Revenue mismatches are quarantined for review because the 100 affected rows have invalid quantities and the original quantities cannot be established from this dataset alone. The other 149,016 unique, positive-quantity rows satisfy `Revenue = transaction_qty * unit_price` within one cent.

In [ ]:
from pathlib import Path
import pandas as pd

# Resolve the project root whether this notebook is launched from the root or notebooks/.
_here = Path.cwd()
PROJECT_ROOT = _here if (_here / "data" / "Coffee_Shop_Sales.xlsx").exists() else _here.parent
SOURCE_PATH = PROJECT_ROOT / "data" / "Coffee_Shop_Sales.xlsx"
CLEAN_PATH = PROJECT_ROOT / "data" / "coffee_shop_cleaned.csv"
REVIEW_PATH = PROJECT_ROOT / "data" / "coffee_shop_review.csv"

source_df = pd.read_excel(SOURCE_PATH, sheet_name="DATA_MESSY")
source_rows = len(source_df)
exact_duplicates = int(source_df.duplicated().sum())
work = source_df.drop_duplicates().copy()

# Normalize whitespace/case in labels. These transformations do not alter IDs.
for column in ["store_location", "product_category", "product_type", "product_detail"]:
    work[column] = work[column].astype("string").str.strip()
for column in ["store_location", "product_category"]:
    work[column] = work[column].str.title()

# Parse currency formatting explicitly; keep a count of values that remain invalid.
price_text = work["unit_price"].astype("string").str.strip()
price_numeric = pd.to_numeric(price_text.str.replace(r"[$,]", "", regex=True), errors="coerce")
price_failures = int((price_numeric.isna() & work["unit_price"].notna()).sum())
work["unit_price"] = price_numeric

# Mixed date strings are parsed flexibly; ISO date values remain unambiguous.
work["transaction_date"] = pd.to_datetime(
    work["transaction_date"].astype("string").str.strip(),
    format="mixed", dayfirst=True, errors="coerce"
)
work["transaction_time"] = pd.to_datetime(
    work["transaction_time"].astype("string").str.strip(),
    format="%H:%M:%S", errors="coerce"
).dt.time

# Use IDs to fill missing labels only after verifying every observed mapping is unique.
for id_column, label_column in [("product_id", "product_category"), ("store_id", "store_location")]:
    mapping_counts = work.dropna(subset=[label_column]).groupby(id_column)[label_column].nunique()
    ambiguous = mapping_counts[mapping_counts > 1]
    if not ambiguous.empty:
        raise ValueError(f"Ambiguous {id_column} to {label_column} mappings: {ambiguous.index.tolist()}")
    mapping = work.dropna(subset=[label_column]).drop_duplicates(id_column).set_index(id_column)[label_column]
    work[label_column] = work[label_column].fillna(work[id_column].map(mapping))

work["transaction_qty"] = pd.to_numeric(work["transaction_qty"], errors="coerce")
work["Revenue"] = pd.to_numeric(work["Revenue"], errors="coerce")

# Preserve every nonpositive quantity row, uncorrected, for investigation.
invalid_quantity = work["transaction_qty"].isna() | work["transaction_qty"].le(0)
review = work.loc[invalid_quantity].copy()
review["review_reason"] = "Quantity missing or nonpositive; quantity/revenue not inferred"
review["expected_revenue_if_quantity_valid"] = review["transaction_qty"] * review["unit_price"]
review["revenue_difference_if_quantity_valid"] = (
    review["Revenue"] - review["expected_revenue_if_quantity_valid"]
)
review.to_csv(REVIEW_PATH, index=False)

# Positive quantities with complete calculation inputs must reconcile; fail loudly otherwise.
calculable = work["transaction_qty"].gt(0) & work["unit_price"].notna() & work["Revenue"].notna()
work["expected_revenue"] = work["transaction_qty"] * work["unit_price"]
work["revenue_difference"] = work["Revenue"] - work["expected_revenue"]
mismatch = calculable & work["revenue_difference"].abs().gt(0.01)
if mismatch.any():
    raise ValueError(f"{int(mismatch.sum())} positive-quantity rows have revenue discrepancies; inspect before export")

# Keep only analytically valid records in the dashboard CSV; all quantity exceptions
# are retained, with original values, in REVIEW_PATH above.
clean = work.loc[~invalid_quantity].copy()
clean.to_csv(CLEAN_PATH, index=False)

print(f"Source rows: {source_rows:,}")
print(f"Exact duplicate rows removed: {exact_duplicates:,}")
print(f"Unique rows after exact deduplication: {len(work):,}")
print(f"Unit prices still failing conversion: {price_failures:,}")
print(f"Nonpositive/missing quantity review rows: {len(review):,}")
print(f"Positive-quantity revenue mismatches (> $0.01): {int(mismatch.sum()):,}")
print(f"Analysis CSV rows: {len(clean):,} -> {CLEAN_PATH}")
print(f"Review CSV rows: {len(review):,} -> {REVIEW_PATH}")